name: Run Python Scripts
on:
  push:
    branches:
      - new-workflows
  workflow_dispatch:
  schedule:
    - cron: '0 8 1 * *'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: new-workflows

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3' 
          cache: 'pip' # caching pip dependencies
      
      - name: Install python dependencies and GitHub CLI
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Run the main bibliography builder
        run: python main.py
      
      - name: Check for files
        run: |
          # Logs and tex-files
          ls -la out/
          # downloaded exports
          ls -ls data/

      - name: Draft Release
        run: |
          # Get today's date in YYYY-MM-DD format
          DATE=$(date +"%Y-%m-%d")
          MONTH=$(date +"%B")
          YEAR=$(date +"%Y")

          # Create a draft release using gh
          gh release create "v$DATE" \
            --title "Release $DATE" \
            --draft \
            --latest \
            --notes "This is the monthly update of the Miletus Bibliography for $MONTH $YEAR." 
            --repo $GITHUB_REPOSITORY

      - name: Add files to release draft
        run: |
          DATE=$(date +"%Y-%m-%d")
          gh release upload "v$DATE" ./out/check_result.log --clobber
