name: Run Python Scripts
on:
  push:
    branches:
      - new-workflows
  workflow_dispatch:
  schedule:
    - cron: '0 8 1 * *'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: new-workflows

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3' 
          cache: 'pip' # caching pip dependencies
      
      - name: Install python dependencies and GitHub CLI
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Run the main bibliography builder
        run: python main.py

      - name: Draft Release
        run: |
          # Get today's date in YYYY-MM-DD format
          DATE=$(date +"%Y-%m-%d")

          # Create a draft release using gh
          gh release create "v$DATE" \
            --title "Release $DATE" \
            --draft \
            --body "This is the update of the bibliography on $DATE ;" \
            --repo $GITHUB_REPOSITORY