name: Process
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 1 * *'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3' 
          cache: 'pip' # caching pip dependencies
      
      - name: Install python dependencies and GitHub CLI
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Run the main bibliography builder
        run: python main.py
      
      - name: Run the HTML-table-builder
        run: python bibliography_convert.py
      
      - name: Check for files
        run: ls -R out/

      - name: Upload Logs
        uses: actions/upload-artifact@v7
        with: 
          name: logs
          path: out/logs/
          retention-days: 31
          overwrite: true
      
      - name: Upload Data
        uses: actions/upload-artifact@v7
        with: 
          name: data
          path: out/data/
          retention-days: 31
          overwrite: true

      - name: Upload Tex Files
        uses: actions/upload-artifact@v7
        with: 
          name: tex
          path: out/tex/
          retention-days: 31
          overwrite: true
