name: Draft Release
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Bibliography"]
    types:
      - completed

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  Python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main
      
      - name: Download Logs
        uses: actions/download-artifact@v8
        with:
          name: logs
          path: out/logs

      - name: Download Data
        uses: actions/download-artifact@v8
        with:
          name: data
          path: out/data

      - name: Download Tex Files
        uses: actions/download-artifact@v8
        with:
          name: tex
          path: out/tex

      - name: Check for files
        run: ls -R out/

      - 

      - name: Draft Release
        run: |
          # Get today's date in YYYY-MM-DD format
          DATE=$(date +"%Y-%m-%d")
          MONTH=$(date +"%B")
          YEAR=$(date +"%Y")

          echo $GH_PAT | gh auth login --with-token

          # Create a draft release using gh
          gh release create "v$DATE" \
            --title "Release $DATE" \
            --draft \
            --latest \
            --notes "This is the monthly update of the Miletus Bibliography for $MONTH $YEAR." 
            --repo $GITHUB_REPOSITORY

      - name: Add files to release draft
        run: |
          DATE=$(date +"%Y-%m-%d")
          echo $GH_PAT | gh auth login --with-token
          gh release upload "v$DATE" ./out/check_result.log #DataChecker-Log --clobber
          gh release upload "v$DATE" ./data/Milet_Bibliography_BibLaTeX.bib --clobber
          gh release upload "v$DATE" ./data/Milet_Bibliography_BibTeX.bib --clobber
          gh release upload "v$DATE" ./data/Milet_Bibliography_CSV.csv --clobber
          gh release upload "v$DATE" ./data/Milet_Bibliography_JSON.json --clobber
          gh release upload "v$DATE" ./data/Milet_Bibliography_RIS.ris --clobber
